name: Digitalevolutions
favicon: null
layout_spectrum: 0.38876932207494974
typography_spectrum: 0.9877181467600167
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6551890845876187
  lightness: 0.4139829392079264
  saturation: 0.6738029262050986
  rhythmicContrast: 0.41911000618711114
purpose: []
